name: All Match Benchmark
 
on:
  push:
    branches:
      - master
 
jobs:
  benchmark:
    name: Benchmark

    strategy:
      matrix:
        java: [ 11 ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build artifacts
        run: mvn clean install

      - name: Create Results dir
        run: mkdir results

      - name: Run Benchmark [COLLECTION_SIZE = 10]
        run: java -jar target/benchmarks.jar -rf text -rff results/results_all_match_10.log -i 10 -wi 10 -f 2 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" AllMatchBenchmark -p COLLECTION_SIZE=10

      - name: Run Benchmark [COLLECTION_SIZE = 1000]
        run: java -jar target/benchmarks.jar -rf text -rff results/results_all_match_1000.log -i 10 -wi 10 -f 2 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" AllMatchBenchmark -p COLLECTION_SIZE=1000

      - name: Run Benchmark [COLLECTION_SIZE = 100000]
        run: java -jar target/benchmarks.jar -rf text -rff results/results_all_match_100000.log -i 10 -wi 10 -f 2 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" AllMatchBenchmark -p COLLECTION_SIZE=100000

      - name: Upload results
        uses: actions/upload-artifact@v1
        with:
          name: results_all_match
          path: results
