name: Benchmark Java sequences
 
on:
  push:
    branches:
      - master
 
jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: Run benchmarks
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean install
      - run: java -jar target/benchmarks.jar -i 10 -wi 10 -f 3 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G"
