name: Benchmark Java sequences
 
on: [push]
 
jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: Run benchmarks
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean install
      - run: java -jar target/jayield-benchmark-0.0.0-SNAPSHOT.jar
