name: Concurrency[11op]

on:
  push:
    branches:
      - concurrency/eleven
      - all-benchmarks

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark
        run: java -jar target/benchmarks.jar -rf text -rff single.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=1" SingleThreadedBenchmark.eleven -p COLLECTION_SIZE=455,545,636,727,818,909,1000,1091,1182,1273,1364 && java -jar target/benchmarks.jar -rf text -rff double.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=2" ParallelBenchmark.eleven -p COLLECTION_SIZE=455,545,636,727,818,909,1000,1091,1182,1273,1364 && java -jar target/benchmarks.jar -rf text -rff quad.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=4" ParallelBenchmark.eleven -p COLLECTION_SIZE=455,545,636,727,818,909,1000,1091,1182,1273,1364

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Concurrency[11op]
          path: ./*.log
