name: Concurrency[9op]

on:
  push:
    branches:
      - concurrency/nine
      - all-benchmarks

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark
        run: java -jar target/benchmarks.jar -rf text -rff single.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=1" 'SingleThreadedBenchmark.nine(?!teen)' -p COLLECTION_SIZE=556,667,778,889,1000,1111,1222,1333,1444,1556,1667 && java -jar target/benchmarks.jar -rf text -rff double.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=2" 'ParallelBenchmark.nine(?!teen)' -p COLLECTION_SIZE=556,667,778,889,1000,1111,1222,1333,1444,1556,1667 && java -jar target/benchmarks.jar -rf text -rff quad.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=4" 'ParallelBenchmark.nine(?!teen)' -p COLLECTION_SIZE=556,667,778,889,1000,1111,1222,1333,1444,1556,1667

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Concurrency[9op]
          path: ./*.log
