name: Concurrency[17op]

on:
  push:
    branches:
      - concurrency/seventeen
      - all-benchmarks

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark
        run: java -jar target/benchmarks.jar -rf text -rff single.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=1" SingleThreadedBenchmark.seventeen -p COLLECTION_SIZE=294,353,412,471,529,588,647,706,765,824,882 && java -jar target/benchmarks.jar -rf text -rff double.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=2" ParallelBenchmark.seventeen -p COLLECTION_SIZE=294,353,412,471,529,588,647,706,765,824,882 && java -jar target/benchmarks.jar -rf text -rff quad.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=4" ParallelBenchmark.seventeen -p COLLECTION_SIZE=294,353,412,471,529,588,647,706,765,824,882

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Concurrency[17op]
          path: ./*.log
