name: Concurrency[15op]

on:
  push:
    branches:
      - concurrency/fifteen
      - all-benchmarks

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark
        run: java -jar target/benchmarks.jar -rf text -rff single.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=1" SingleThreadedBenchmark.fifteen -p COLLECTION_SIZE=333,400,467,533,600,667,733,800,867,933,1000 && java -jar target/benchmarks.jar -rf text -rff double.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=2" ParallelBenchmark.fifteen -p COLLECTION_SIZE=333,400,467,533,600,667,733,800,867,933,1000 && java -jar target/benchmarks.jar -rf text -rff quad.log -i 5 -wi 2 -f 1 -r 60 -w 60 --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=4" ParallelBenchmark.fifteen -p COLLECTION_SIZE=333,400,467,533,600,667,733,800,867,933,1000

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Concurrency[15op]
          path: ./*.log
