name: 10 EveryClassBenchmark
 
on:
  push:
    branches:
      - every/class
      - all-benchmarks
 
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark [COLLECTION_SIZE = 10]
        run: java -jar target/benchmarks.jar -rf text -rff results.log -i 10 -wi 10 -f 3 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" EveryClassBenchmark -p COLLECTION_SIZE=10

      - name: Upload results
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: results.log
