name: Find[Fixed_Index]

on:
  push:
    branches:
      - find/fixed-index
      - all-benchmarks

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build artifacts
        run: mvn clean install -Dgpg.skip

      - name: Run Benchmark [COLLECTION_SIZE = 1K]
        run: java -jar target/benchmarks.jar -rf text -rff Find[Fixed_Index]-1K.log -i 10 -wi 10 -f 3 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" FindFixedIndexBenchmark -p COLLECTION_SIZE=1000

      - name: Run Benchmark [COLLECTION_SIZE = 100K]
        run: java -jar target/benchmarks.jar -rf text -rff Find[Fixed_Index]-100K.log -i 10 -wi 10 -f 3 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" FindFixedIndexBenchmark -p COLLECTION_SIZE=100000

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Find[Fixed_Index]
          path: ./*.log
