name: First[Middle]
 
on:
  push:
    branches:
      - first/middle
      - all-benchmarks
 
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark [COLLECTION_SIZE = 1K]
        run: java -jar target/benchmarks.jar -rf text -rff First[Middle]-1K.log -i 10 -wi 10 -f 3 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" FindFirstInMiddleBenchmark -p COLLECTION_SIZE=1000

      - name: Run Benchmark [COLLECTION_SIZE = 100K]
        run: java -jar target/benchmarks.jar -rf text -rff First[Middle]-100K.log -i 10 -wi 10 -f 3 -r 15 -w 20 --jvmArgs "-Xms2G -Xmx2G" FindFirstInMiddleBenchmark -p COLLECTION_SIZE=100000

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: First[Middle]
          path: ./*.log
